---
title: "Projects"
format: html
---
## Research
### Methylation Patterns and Liver Disease Detection

<strong>Manuscript</strong>: A Highly Cost-Effective Cell-Free DNA Methylome Test for the Simultaneous Detection of Multiple Diseases. Zeng W, Liu CC, Li S,..., ..., <strong>Tang C</strong>, ...., Li W, Zhou XJ.  
(To be submitted in early 2025)


<ul>
  <li>Wrote and utilized ML models to process patient cell-free methylation data and mass spectrometry data to explore new clinical biomarkers and diagnostic tools for liver disease detection</li>
  <li>Evaluated non-invasive diagnostic methods on 200 Hepatitis B (HBV) patients using regression and classification models on patient methylation data</li>
  <li>Explored predictive models for clinical parameters utilized in liver disease diagnosis and detection</li>
  <li>Initiating and fostering collaboration with other labs overseeing mass spectrometry data for proteomics analysis and biomarker discovery</li>
</ul>



### Alzheimer's Disease
<ul>
  <li>Built a ML model to create a personalized diagnosis for Alzheimer’s Disease based on biomarkers</li>
  <li>Initiated a secondary analysis on the biomarker and imaging data of over 5000 patients in the Alzheimer’s Disease Neuroimaging Initiative (ADNI) database</li>
  <li>Investigated the relationship of cerebral spinal fluid on Amyloid Beta protein aggregation</li>
  <li>Led a sequencing team studying mutational effects on protein aggregation with deep mutagenesis & sequencing</li>
</ul>





## Academic
### ECE C147/C247 Final Project
For my final project in ECE C147/247 (Winter 2025) with Professor Jonathan Kao, I worked on implementing a machine learning model for predicting QWERTY typing patterns using surface electromyography (sEMG) signals. The project builds upon the emg2qwerty framework developed by Meta, which provides a large dataset of sEMG recordings while typing on a QWERTY keyboard. Working from a baseline model we explored various implementations including CNN+GRU and CNN+BiLSTM Hybrid models alongside various preprocessing techniques and transformers.

[Read full project document here](files/C147_247.pdf)


### COMAP Competition
COMAP, the Consortium for Mathematics and Its Applications, is an award-winning non-profit organization dedicated to enhancing mathematics education, particularly through the promotion of mathematical modeling. This year, my team and I devised a model for a sustainable tourism industry in Juneau, Alaska by balancing visitor numbers, revenue, and tourism stabilization measures using an agent-node representation with weighted edges.
[Read full project document here](files/COMAP_2025.pdf)
